import { Item } from "../components/Badges";

export const languages: Item[] = [
  { id: "ar", name: "Arabic" },
  { id: "de", name: "German" },
  { id: "en", name: "English" },
  { id: "es", name: "Spanish" },
  { id: "fr", name: "French" },
  { id: "he", name: "Hebrew" },
  { id: "it", name: "Italian" },
  { id: "nl", name: "Dutch" },
  { id: "no", name: "Norwegian" },
  { id: "pt", name: "Portuguese" },
  { id: "ru", name: "Russian" },
  { id: "sv", name: "Swedish" },
  { id: "zh", name: "Chinese" },
];

export const countries: Item[] = [
  { id: "ar", name: "Argentina" },
  { id: "au", name: "Australia" },
  { id: "at", name: "Austria" },
  { id: "be", name: "Belgium" },
  { id: "br", name: "Brazil" },
  { id: "bg", name: "Bulgaria" },
  { id: "ca", name: "Canada" },
  { id: "cn", name: "China" },
  { id: "co", name: "Colombia" },
  { id: "cu", name: "Cuba" },
  { id: "cz", name: "Czech Republic" },
  { id: "eg", name: "Egypt" },
  { id: "fr", name: "France" },
  { id: "de", name: "Germany" },
  { id: "gr", name: "Greece" },
  { id: "hk", name: "Hong Kong" },
  { id: "hu", name: "Hungary" },
  { id: "in", name: "India" },
  { id: "id", name: "Indonesia" },
  { id: "ie", name: "Ireland" },
  { id: "il", name: "Israel" },
  { id: "it", name: "Italy" },
  { id: "jp", name: "Japan" },
  { id: "lv", name: "Latvia" },
  { id: "lt", name: "Lithuania" },
  { id: "my", name: "Malaysia" },
  { id: "mx", name: "Mexico" },
  { id: "ma", name: "Morocco" },
  { id: "nl", name: "Netherlands" },
  { id: "nz", name: "New Zealand" },
  { id: "ng", name: "Nigeria" },
  { id: "no", name: "Norway" },
  { id: "ph", name: "Philippines" },
  { id: "pl", name: "Poland" },
  { id: "pt", name: "Portugal" },
  { id: "ro", name: "Romania" },
  { id: "ru", name: "Russia" },
  { id: "sa", name: "Saudi Arabia" },
  { id: "rs", name: "Serbia" },
  { id: "sg", name: "Singapore" },
  { id: "sk", name: "Slovakia" },
  { id: "si", name: "Slovenia" },
  { id: "za", name: "South Africa" },
  { id: "kr", name: "South Korea" },
  { id: "se", name: "Sweden" },
  { id: "ch", name: "Switzerland" },
  { id: "tw", name: "Taiwan" },
  { id: "th", name: "Thailand" },
  { id: "tr", name: "Turkey" },
  { id: "ae", name: "UAE" },
  { id: "ua", name: "Ukraine" },
  { id: "gb", name: "United Kingdom" },
  { id: "us", name: "United States" },
  { id: "ve", name: "Venezuela" },
];
